-- ============================================================
-- 002 — Sync Support
-- Adds updated_at tracking to workout tables and seeds exercises
-- ============================================================

-- ── updated_at columns ────────────────────────────────────────────────────────

ALTER TABLE workout_sessions   ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE session_exercises  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE sets               ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_ws_updated_at
  BEFORE UPDATE ON workout_sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_se_updated_at
  BEFORE UPDATE ON session_exercises
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sets_updated_at
  BEFORE UPDATE ON sets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── Unique index for built-in exercise names (enables ON CONFLICT upsert) ─────

CREATE UNIQUE INDEX IF NOT EXISTS idx_exercises_name_builtin
  ON exercises(name) WHERE (NOT is_custom);

-- ── Seed built-in exercises ───────────────────────────────────────────────────

INSERT INTO exercises (name, muscle_primary, muscle_secondary, equipment, is_custom) VALUES
  -- CHEST
  ('Barbell Bench Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'barbell', false),
  ('Incline Barbell Bench Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'barbell', false),
  ('Decline Barbell Bench Press', ARRAY['chest'], ARRAY['triceps'], 'barbell', false),
  ('Paused Bench Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'barbell', false),
  ('Close Grip Bench Press', ARRAY['triceps'], ARRAY['chest','front_delt'], 'barbell', false),
  ('Dumbbell Bench Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'dumbbell', false),
  ('Incline Dumbbell Bench Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'dumbbell', false),
  ('Decline Dumbbell Bench Press', ARRAY['chest'], ARRAY['triceps'], 'dumbbell', false),
  ('Dumbbell Flye', ARRAY['chest'], ARRAY['front_delt'], 'dumbbell', false),
  ('Incline Dumbbell Flye', ARRAY['chest'], ARRAY['front_delt'], 'dumbbell', false),
  ('Decline Dumbbell Flye', ARRAY['chest'], ARRAY['front_delt'], 'dumbbell', false),
  ('Dumbbell Pull Over', ARRAY['chest'], ARRAY['lats','triceps'], 'dumbbell', false),
  ('Cable Crossover', ARRAY['chest'], ARRAY['front_delt'], 'cable', false),
  ('Low Cable Crossover', ARRAY['chest'], ARRAY['front_delt'], 'cable', false),
  ('High Cable Crossover', ARRAY['chest'], ARRAY['front_delt'], 'cable', false),
  ('Incline Cable Fly', ARRAY['chest'], ARRAY['front_delt'], 'cable', false),
  ('Cable Fly (Mid)', ARRAY['chest'], ARRAY['front_delt'], 'cable', false),
  ('Cable Pull Over', ARRAY['chest'], ARRAY['lats'], 'cable', false),
  ('Push-Up', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Wide Push-Up', ARRAY['chest'], ARRAY['triceps'], null, false),
  ('Decline Push-Up', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Incline Push-Up', ARRAY['chest'], ARRAY['triceps'], null, false),
  ('Weighted Push-Up', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Diamond Push-Up', ARRAY['triceps'], ARRAY['chest'], null, false),
  ('Archer Push-Up', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Clap Push-Up', ARRAY['chest'], ARRAY['triceps'], null, false),
  ('One-Arm Push-Up', ARRAY['chest'], ARRAY['triceps','core'], null, false),
  ('Ring Push-Up', ARRAY['chest'], ARRAY['triceps','core'], null, false),
  ('Dips', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Weighted Dip', ARRAY['chest'], ARRAY['triceps','front_delt'], null, false),
  ('Machine Chest Press', ARRAY['chest'], ARRAY['triceps'], 'machine', false),
  ('Incline Machine Chest Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'machine', false),
  ('Pec Deck', ARRAY['chest'], ARRAY[]::text[], 'machine', false),
  ('Machine Chest Fly', ARRAY['chest'], ARRAY['front_delt'], 'machine', false),
  ('Machine Pull Over', ARRAY['chest'], ARRAY['lats'], 'machine', false),
  ('Machine Dip', ARRAY['chest'], ARRAY['triceps'], 'machine', false),
  ('Smith Machine Bench Press', ARRAY['chest'], ARRAY['triceps'], 'smith_machine', false),
  ('Smith Machine Incline Press', ARRAY['chest'], ARRAY['triceps','front_delt'], 'smith_machine', false),
  ('Smith Machine Decline Press', ARRAY['chest'], ARRAY['triceps'], 'smith_machine', false),
  ('Landmine Press', ARRAY['chest'], ARRAY['front_delt','triceps'], 'barbell', false),
  ('Svend Press', ARRAY['chest'], ARRAY[]::text[], null, false),
  ('JM Press', ARRAY['triceps'], ARRAY['chest'], 'barbell', false),
  -- BACK
  ('Deadlift', ARRAY['lower_back','glutes'], ARRAY['hamstrings','traps','lats'], 'barbell', false),
  ('Romanian Deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'barbell', false),
  ('Sumo Deadlift', ARRAY['glutes','hamstrings'], ARRAY['lower_back','quads'], 'barbell', false),
  ('Deficit Deadlift', ARRAY['lower_back','glutes'], ARRAY['hamstrings','quads'], 'barbell', false),
  ('Stiff Leg Deadlift', ARRAY['hamstrings','lower_back'], ARRAY['glutes'], 'barbell', false),
  ('Trap Bar Deadlift', ARRAY['quads','glutes'], ARRAY['lower_back','hamstrings','traps'], 'trap_bar', false),
  ('Rack Pull', ARRAY['lower_back','traps'], ARRAY['glutes','lats'], 'barbell', false),
  ('Good Morning', ARRAY['lower_back','hamstrings'], ARRAY['glutes'], 'barbell', false),
  ('Jefferson Curl', ARRAY['lower_back','hamstrings'], ARRAY[]::text[], 'barbell', false),
  ('Suitcase Deadlift', ARRAY['core','lower_back'], ARRAY['glutes','hamstrings'], 'dumbbell', false),
  ('Barbell Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('Pendlay Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('T-Bar Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('Meadows Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('Landmine Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('Dumbbell Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'dumbbell', false),
  ('Single Arm Dumbbell Row', ARRAY['lats','mid_back'], ARRAY['biceps','rear_delt'], 'dumbbell', false),
  ('Kroc Row', ARRAY['lats','mid_back'], ARRAY['biceps','traps'], 'dumbbell', false),
  ('Chest-Supported Dumbbell Row', ARRAY['mid_back'], ARRAY['lats','rear_delt'], 'dumbbell', false),
  ('Seal Row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'barbell', false),
  ('Inverted Row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], null, false),
  ('Pull-Up', ARRAY['lats'], ARRAY['biceps','mid_back'], null, false),
  ('Chin-Up', ARRAY['lats','biceps'], ARRAY['mid_back'], null, false),
  ('Neutral Grip Pull-Up', ARRAY['lats'], ARRAY['biceps'], null, false),
  ('Close Grip Pull-Up', ARRAY['lats','biceps'], ARRAY['mid_back'], null, false),
  ('Wide Grip Pull-Up', ARRAY['lats'], ARRAY['mid_back'], null, false),
  ('Typewriter Pull-Up', ARRAY['lats'], ARRAY['biceps','mid_back'], null, false),
  ('Archer Pull-Up', ARRAY['lats'], ARRAY['biceps','mid_back'], null, false),
  ('Weighted Pull-Up', ARRAY['lats'], ARRAY['biceps','mid_back'], null, false),
  ('Assisted Pull-Up', ARRAY['lats'], ARRAY['biceps','mid_back'], 'machine', false),
  ('Lat Pulldown', ARRAY['lats'], ARRAY['biceps','mid_back'], 'cable', false),
  ('Wide Grip Lat Pulldown', ARRAY['lats'], ARRAY['mid_back'], 'cable', false),
  ('Close Grip Lat Pulldown', ARRAY['lats'], ARRAY['biceps'], 'cable', false),
  ('Neutral Grip Lat Pulldown', ARRAY['lats'], ARRAY['biceps'], 'cable', false),
  ('Reverse Grip Lat Pulldown', ARRAY['lats','biceps'], ARRAY['mid_back'], 'cable', false),
  ('Single Arm Lat Pulldown', ARRAY['lats'], ARRAY['biceps'], 'cable', false),
  ('Straight Arm Pulldown', ARRAY['lats'], ARRAY['triceps'], 'cable', false),
  ('Rope Straight Arm Pulldown', ARRAY['lats'], ARRAY[]::text[], 'cable', false),
  ('Seated Cable Row', ARRAY['mid_back'], ARRAY['lats','biceps'], 'cable', false),
  ('Single Arm Cable Row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'cable', false),
  ('Wide Grip Cable Row', ARRAY['lats','mid_back'], ARRAY['rear_delt'], 'cable', false),
  ('Face Pull', ARRAY['rear_delt','traps'], ARRAY['mid_back'], 'cable', false),
  ('Machine Row', ARRAY['mid_back','lats'], ARRAY['biceps'], 'machine', false),
  ('Chest Supported Machine Row', ARRAY['mid_back','lats'], ARRAY['biceps','rear_delt'], 'machine', false),
  ('High Row Machine', ARRAY['lats','mid_back'], ARRAY['biceps'], 'machine', false),
  ('Smith Machine Row', ARRAY['lats','mid_back'], ARRAY['biceps'], 'smith_machine', false),
  ('Back Extension', ARRAY['lower_back'], ARRAY['glutes','hamstrings'], null, false),
  ('Hyperextension', ARRAY['lower_back'], ARRAY['glutes','hamstrings'], null, false),
  ('Reverse Hyperextension', ARRAY['glutes','hamstrings'], ARRAY['lower_back'], 'machine', false),
  ('Shrugs', ARRAY['traps'], ARRAY[]::text[], 'barbell', false),
  ('Dumbbell Shrugs', ARRAY['traps'], ARRAY[]::text[], 'dumbbell', false),
  ('Cable Shrug', ARRAY['traps'], ARRAY[]::text[], 'cable', false),
  ('Trap Bar Shrug', ARRAY['traps'], ARRAY[]::text[], 'trap_bar', false),
  ('Smith Machine Shrug', ARRAY['traps'], ARRAY[]::text[], 'smith_machine', false),
  ('Dead Hang', ARRAY['lats','forearms'], ARRAY['mid_back'], null, false),
  ('Active Dead Hang', ARRAY['lats','mid_back'], ARRAY['forearms'], null, false),
  -- SHOULDERS
  ('Overhead Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps','traps'], 'barbell', false),
  ('Push Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps','quads'], 'barbell', false),
  ('Z Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps','core'], 'barbell', false),
  ('Seated Dumbbell Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps'], 'dumbbell', false),
  ('Arnold Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps'], 'dumbbell', false),
  ('Lateral Raise', ARRAY['mid_delt'], ARRAY[]::text[], 'dumbbell', false),
  ('Seated Lateral Raise', ARRAY['mid_delt'], ARRAY[]::text[], 'dumbbell', false),
  ('Cable Lateral Raise', ARRAY['mid_delt'], ARRAY[]::text[], 'cable', false),
  ('Front Raise', ARRAY['front_delt'], ARRAY[]::text[], 'dumbbell', false),
  ('Barbell Front Raise', ARRAY['front_delt'], ARRAY[]::text[], 'barbell', false),
  ('Rear Delt Flye', ARRAY['rear_delt'], ARRAY['mid_back'], 'dumbbell', false),
  ('Reverse Cable Flye', ARRAY['rear_delt'], ARRAY['mid_back'], 'cable', false),
  ('Reverse Pec Deck', ARRAY['rear_delt'], ARRAY['mid_back'], 'machine', false),
  ('Machine Rear Delt Fly', ARRAY['rear_delt'], ARRAY['mid_back'], 'machine', false),
  ('Machine Shoulder Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps'], 'machine', false),
  ('Machine Lateral Raise', ARRAY['mid_delt'], ARRAY[]::text[], 'machine', false),
  ('Smith Machine Overhead Press', ARRAY['front_delt','mid_delt'], ARRAY['triceps'], 'smith_machine', false),
  ('Upright Row', ARRAY['mid_delt','traps'], ARRAY['biceps'], 'barbell', false),
  ('Cable Upright Row', ARRAY['mid_delt','traps'], ARRAY['biceps'], 'cable', false),
  ('Pike Push-Up', ARRAY['front_delt'], ARRAY['triceps'], null, false),
  ('Handstand Push-Up', ARRAY['front_delt','mid_delt'], ARRAY['triceps','traps'], null, false),
  ('Freestanding Handstand Push-Up', ARRAY['front_delt','mid_delt'], ARRAY['triceps','core'], null, false),
  ('Landmine Lateral Raise', ARRAY['mid_delt'], ARRAY[]::text[], 'barbell', false),
  ('Cuban Press', ARRAY['rear_delt','mid_delt'], ARRAY['traps','front_delt'], 'dumbbell', false),
  ('Lu Raise', ARRAY['mid_delt','rear_delt'], ARRAY[]::text[], 'dumbbell', false),
  ('Band Pull Apart', ARRAY['rear_delt'], ARRAY['mid_back'], 'resistance_band', false),
  ('Cable External Rotation', ARRAY['rear_delt'], ARRAY['mid_back'], 'cable', false),
  ('Cable Internal Rotation', ARRAY['front_delt'], ARRAY[]::text[], 'cable', false),
  ('Prone Y Raise', ARRAY['rear_delt','traps'], ARRAY[]::text[], null, false),
  ('Prone T Raise', ARRAY['rear_delt','mid_back'], ARRAY[]::text[], null, false),
  ('Prone W Raise', ARRAY['rear_delt','mid_back'], ARRAY[]::text[], null, false),
  -- BICEPS
  ('Barbell Curl', ARRAY['biceps'], ARRAY['forearms'], 'barbell', false),
  ('EZ Bar Curl', ARRAY['biceps'], ARRAY['forearms'], 'barbell', false),
  ('Reverse EZ Bar Curl', ARRAY['brachialis','forearms'], ARRAY['biceps'], 'barbell', false),
  ('Dumbbell Curl', ARRAY['biceps'], ARRAY['forearms'], 'dumbbell', false),
  ('Alternating Dumbbell Curl', ARRAY['biceps'], ARRAY['forearms'], 'dumbbell', false),
  ('Hammer Curl', ARRAY['biceps','brachialis'], ARRAY['forearms'], 'dumbbell', false),
  ('Cross Body Hammer Curl', ARRAY['brachialis','biceps'], ARRAY['forearms'], 'dumbbell', false),
  ('Incline Dumbbell Curl', ARRAY['biceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Concentration Curl', ARRAY['biceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Spider Curl', ARRAY['biceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Zottman Curl', ARRAY['biceps','brachialis'], ARRAY['forearms'], 'dumbbell', false),
  ('Drag Curl', ARRAY['biceps'], ARRAY[]::text[], 'barbell', false),
  ('Cable Curl', ARRAY['biceps'], ARRAY['forearms'], 'cable', false),
  ('Cable Hammer Curl', ARRAY['biceps','brachialis'], ARRAY[]::text[], 'cable', false),
  ('Bayesian Curl', ARRAY['biceps'], ARRAY[]::text[], 'cable', false),
  ('Preacher Curl', ARRAY['biceps'], ARRAY[]::text[], 'barbell', false),
  ('Dumbbell Preacher Curl', ARRAY['biceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Machine Curl', ARRAY['biceps'], ARRAY[]::text[], 'machine', false),
  ('Reverse Curl', ARRAY['brachialis','forearms'], ARRAY['biceps'], 'barbell', false),
  ('21s Curl', ARRAY['biceps'], ARRAY[]::text[], 'barbell', false),
  -- TRICEPS
  ('Skull Crusher', ARRAY['triceps'], ARRAY[]::text[], 'barbell', false),
  ('EZ Bar Skull Crusher', ARRAY['triceps'], ARRAY[]::text[], 'barbell', false),
  ('Dumbbell Skull Crusher', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Tricep Pushdown', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('Rope Tricep Pushdown', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('Reverse Grip Tricep Pushdown', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('One Arm Tricep Pushdown', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('Overhead Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Cable Overhead Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('Single Arm Overhead Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Rope Overhead Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'cable', false),
  ('Tricep Kickback', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', false),
  ('Bench Dip', ARRAY['triceps'], ARRAY['front_delt'], null, false),
  ('Machine Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'machine', false),
  ('Tate Press', ARRAY['triceps'], ARRAY[]::text[], 'dumbbell', false),
  ('California Press', ARRAY['triceps'], ARRAY[]::text[], 'barbell', false),
  ('Ring Dip', ARRAY['chest','triceps'], ARRAY['front_delt'], null, false),
  -- QUADS
  ('Barbell Back Squat', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'barbell', false),
  ('Barbell Front Squat', ARRAY['quads'], ARRAY['glutes','core'], 'barbell', false),
  ('Box Squat', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'barbell', false),
  ('Pause Squat', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'barbell', false),
  ('Zercher Squat', ARRAY['quads','glutes'], ARRAY['core','biceps'], 'barbell', false),
  ('Safety Bar Squat', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'barbell', false),
  ('Goblet Squat', ARRAY['quads'], ARRAY['glutes','core'], 'dumbbell', false),
  ('Sumo Squat', ARRAY['quads','glutes'], ARRAY['hamstrings','hip_flexors'], 'dumbbell', false),
  ('Cossack Squat', ARRAY['quads','glutes'], ARRAY['hamstrings','hip_flexors'], null, false),
  ('Pistol Squat', ARRAY['quads','glutes'], ARRAY['hamstrings','core'], null, false),
  ('Shrimp Squat', ARRAY['quads','glutes'], ARRAY['hamstrings'], null, false),
  ('Leg Press', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'machine', false),
  ('Leg Press (Wide Stance)', ARRAY['glutes','quads'], ARRAY['hamstrings'], 'machine', false),
  ('Leg Press (Narrow Stance)', ARRAY['quads'], ARRAY['glutes'], 'machine', false),
  ('Hack Squat', ARRAY['quads'], ARRAY['glutes'], 'machine', false),
  ('Belt Squat', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'machine', false),
  ('Pendulum Squat', ARRAY['quads'], ARRAY['glutes'], 'machine', false),
  ('Leg Extension', ARRAY['quads'], ARRAY[]::text[], 'machine', false),
  ('Single Leg Extension', ARRAY['quads'], ARRAY[]::text[], 'machine', false),
  ('Bulgarian Split Squat', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', false),
  ('Front Foot Elevated Split Squat', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', false),
  ('Lunges', ARRAY['quads','glutes'], ARRAY['hamstrings'], null, false),
  ('Reverse Lunge', ARRAY['quads','glutes'], ARRAY['hamstrings'], null, false),
  ('Lateral Lunge', ARRAY['quads','glutes'], ARRAY['hip_flexors'], null, false),
  ('Curtsy Lunge', ARRAY['glutes','quads'], ARRAY['hip_flexors'], null, false),
  ('Walking Lunges', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', false),
  ('Step-Up', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'dumbbell', false),
  ('Sissy Squat', ARRAY['quads'], ARRAY[]::text[], null, false),
  ('Wall Sit', ARRAY['quads'], ARRAY['glutes'], null, false),
  ('Jump Squat', ARRAY['quads','glutes'], ARRAY['calves','hamstrings'], null, false),
  ('Landmine Squat', ARRAY['quads','glutes'], ARRAY['core'], 'barbell', false),
  ('Smith Machine Squat', ARRAY['quads'], ARRAY['glutes','hamstrings'], 'smith_machine', false),
  ('Smith Machine Lunges', ARRAY['quads','glutes'], ARRAY['hamstrings'], 'smith_machine', false),
  -- HAMSTRINGS & GLUTES
  ('Hip Thrust', ARRAY['glutes'], ARRAY['hamstrings'], 'barbell', false),
  ('Dumbbell Hip Thrust', ARRAY['glutes'], ARRAY['hamstrings'], 'dumbbell', false),
  ('Single Leg Hip Thrust', ARRAY['glutes'], ARRAY['hamstrings'], null, false),
  ('Cable Hip Thrust', ARRAY['glutes'], ARRAY['hamstrings'], 'cable', false),
  ('Smith Machine Hip Thrust', ARRAY['glutes'], ARRAY['hamstrings'], 'smith_machine', false),
  ('Glute Bridge', ARRAY['glutes'], ARRAY['hamstrings'], null, false),
  ('Frog Pump', ARRAY['glutes'], ARRAY[]::text[], null, false),
  ('Lying Leg Curl', ARRAY['hamstrings'], ARRAY[]::text[], 'machine', false),
  ('Seated Leg Curl', ARRAY['hamstrings'], ARRAY[]::text[], 'machine', false),
  ('Single Leg Leg Curl', ARRAY['hamstrings'], ARRAY[]::text[], 'machine', false),
  ('Nordic Curl', ARRAY['hamstrings'], ARRAY['glutes'], null, false),
  ('Glute Ham Raise', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'machine', false),
  ('Cable Pull-Through', ARRAY['glutes','hamstrings'], ARRAY['lower_back'], 'cable', false),
  ('Dumbbell Romanian Deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'dumbbell', false),
  ('Single Leg Romanian Deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'dumbbell', false),
  ('Smith Machine Romanian Deadlift', ARRAY['hamstrings','glutes'], ARRAY['lower_back'], 'smith_machine', false),
  ('Glute Kickback Machine', ARRAY['glutes'], ARRAY['hamstrings'], 'machine', false),
  ('Hip Abduction Machine', ARRAY['glutes'], ARRAY['hip_flexors'], 'machine', false),
  ('Hip Adduction Machine', ARRAY['glutes','hip_flexors'], ARRAY[]::text[], 'machine', false),
  ('Cable Hip Abduction', ARRAY['glutes'], ARRAY[]::text[], 'cable', false),
  ('Donkey Kick', ARRAY['glutes'], ARRAY['hamstrings'], null, false),
  ('Fire Hydrant', ARRAY['glutes'], ARRAY[]::text[], null, false),
  ('Clamshell', ARRAY['glutes'], ARRAY[]::text[], null, false),
  ('Kettlebell Swing', ARRAY['glutes','hamstrings'], ARRAY['lower_back','core'], 'kettlebell', false),
  -- CALVES
  ('Standing Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'machine', false),
  ('Seated Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'machine', false),
  ('Leg Press Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'machine', false),
  ('Dumbbell Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'dumbbell', false),
  ('Single Leg Calf Raise', ARRAY['calves'], ARRAY[]::text[], null, false),
  ('Donkey Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'machine', false),
  ('Smith Machine Calf Raise', ARRAY['calves'], ARRAY[]::text[], 'smith_machine', false),
  ('Tibia Raise', ARRAY['calves'], ARRAY[]::text[], null, false),
  -- CORE
  ('Plank', ARRAY['core'], ARRAY['glutes'], null, false),
  ('Side Plank', ARRAY['core','obliques'], ARRAY[]::text[], null, false),
  ('Copenhagen Plank', ARRAY['core','obliques'], ARRAY['glutes','hip_flexors'], null, false),
  ('Crunch', ARRAY['core'], ARRAY[]::text[], null, false),
  ('Cable Crunch', ARRAY['core'], ARRAY[]::text[], 'cable', false),
  ('Hanging Leg Raise', ARRAY['core','hip_flexors'], ARRAY[]::text[], null, false),
  ('Toes to Bar', ARRAY['core','hip_flexors'], ARRAY['lats'], null, false),
  ('Knee to Elbow (Hanging)', ARRAY['core','obliques'], ARRAY['hip_flexors'], null, false),
  ('Lying Leg Raise', ARRAY['core','hip_flexors'], ARRAY[]::text[], null, false),
  ('Ab Wheel Rollout', ARRAY['core'], ARRAY['lats'], null, false),
  ('Barbell Rollout', ARRAY['core'], ARRAY['lats'], 'barbell', false),
  ('Dragon Flag', ARRAY['core'], ARRAY['hip_flexors','glutes'], null, false),
  ('L-Sit', ARRAY['core','hip_flexors'], ARRAY['triceps'], null, false),
  ('Russian Twist', ARRAY['obliques','core'], ARRAY[]::text[], null, false),
  ('Dead Bug', ARRAY['core'], ARRAY[]::text[], null, false),
  ('Bird Dog', ARRAY['core','lower_back'], ARRAY['glutes'], null, false),
  ('Pallof Press', ARRAY['core','obliques'], ARRAY[]::text[], 'cable', false),
  ('Landmine Rotation', ARRAY['obliques','core'], ARRAY['front_delt'], 'barbell', false),
  ('Sit-Up', ARRAY['core'], ARRAY['hip_flexors'], null, false),
  ('Decline Sit-Up', ARRAY['core'], ARRAY['hip_flexors'], null, false),
  ('Hollow Hold', ARRAY['core'], ARRAY[]::text[], null, false),
  ('Hollow Body Rock', ARRAY['core'], ARRAY[]::text[], null, false),
  ('V-Up', ARRAY['core'], ARRAY['hip_flexors'], null, false),
  ('Mountain Climber', ARRAY['core'], ARRAY['hip_flexors','chest'], null, false),
  ('Woodchop', ARRAY['obliques','core'], ARRAY['front_delt'], 'cable', false),
  ('Stir the Pot', ARRAY['core'], ARRAY[]::text[], null, false),
  ('McGill Curl Up', ARRAY['core'], ARRAY[]::text[], null, false),
  -- CALISTHENICS
  ('Muscle-Up (Bar)', ARRAY['lats','chest'], ARRAY['triceps','biceps','core'], null, false),
  ('Muscle-Up (Ring)', ARRAY['lats','chest'], ARRAY['triceps','biceps','core'], null, false),
  ('Front Lever', ARRAY['lats','core'], ARRAY['mid_back','biceps'], null, false),
  ('Front Lever Row', ARRAY['lats','mid_back'], ARRAY['biceps','core'], null, false),
  ('Front Lever Pull-Up', ARRAY['lats','core'], ARRAY['biceps','mid_back'], null, false),
  ('Back Lever', ARRAY['lats','chest'], ARRAY['biceps','core'], null, false),
  ('Skin the Cat', ARRAY['lats','chest'], ARRAY['front_delt','core'], null, false),
  ('Ring Support Hold', ARRAY['chest','triceps'], ARRAY['core','front_delt'], null, false),
  ('Pseudo Planche Push-Up', ARRAY['front_delt','chest'], ARRAY['triceps','core'], null, false),
  ('Tucked Planche Hold', ARRAY['front_delt','chest'], ARRAY['core','triceps'], null, false),
  ('Handstand Hold (Wall)', ARRAY['front_delt','mid_delt'], ARRAY['core','triceps'], null, false),
  ('Freestanding Handstand Hold', ARRAY['front_delt','mid_delt'], ARRAY['core','triceps'], null, false),
  ('Wall Walk', ARRAY['front_delt','mid_delt'], ARRAY['core','chest'], null, false),
  ('Pike Walk', ARRAY['core','front_delt'], ARRAY['hamstrings'], null, false),
  ('Bear Crawl', ARRAY['core','front_delt'], ARRAY['quads','triceps'], null, false),
  ('Crab Walk', ARRAY['core','triceps'], ARRAY['glutes','front_delt'], null, false),
  -- FULL BODY
  ('Power Clean', ARRAY['glutes','hamstrings'], ARRAY['traps','core','quads'], 'barbell', false),
  ('Hang Clean', ARRAY['glutes','hamstrings'], ARRAY['traps','core'], 'barbell', false),
  ('Power Snatch', ARRAY['glutes','hamstrings'], ARRAY['traps','core','front_delt'], 'barbell', false),
  ('Thruster', ARRAY['quads','front_delt'], ARRAY['glutes','triceps'], 'barbell', false),
  ('Clean and Press', ARRAY['glutes','front_delt'], ARRAY['quads','traps','triceps'], 'barbell', false),
  ('Farmer''s Carry', ARRAY['traps','forearms'], ARRAY['core','glutes'], 'dumbbell', false),
  ('Suitcase Carry', ARRAY['core','obliques'], ARRAY['traps','forearms'], 'dumbbell', false),
  ('Turkish Get-Up', ARRAY['core','glutes'], ARRAY['front_delt','quads'], 'kettlebell', false),
  ('Burpee', ARRAY['chest','quads'], ARRAY['core','front_delt'], null, false),
  ('Landmine Hip Hinge', ARRAY['glutes','hamstrings'], ARRAY['lower_back'], 'barbell', false),
  -- CARDIO
  ('Treadmill', ARRAY['quads','calves'], ARRAY['hamstrings','glutes'], 'machine', false),
  ('Rowing Machine', ARRAY['lats','mid_back'], ARRAY['hamstrings','glutes','biceps'], 'machine', false),
  ('Stationary Bike', ARRAY['quads','hamstrings'], ARRAY['glutes','calves'], 'machine', false),
  ('Stair Climber', ARRAY['glutes','quads'], ARRAY['calves','hamstrings'], 'machine', false),
  ('Ski Erg', ARRAY['lats','core'], ARRAY['traps','triceps'], 'machine', false),
  ('Assault Bike', ARRAY['quads','front_delt'], ARRAY['core','hamstrings'], 'machine', false),
  ('Elliptical', ARRAY['quads','glutes'], ARRAY['hamstrings','calves'], 'machine', false),
  ('Jump Rope', ARRAY['calves'], ARRAY['core','front_delt'], null, false),
  ('Box Jump', ARRAY['quads','glutes'], ARRAY['calves','hamstrings'], null, false),
  ('Battle Ropes', ARRAY['front_delt','core'], ARRAY['traps','biceps'], null, false),
  ('Sled Push', ARRAY['quads','glutes'], ARRAY['calves','core'], null, false),
  ('Sled Drag', ARRAY['hamstrings','glutes'], ARRAY['lower_back','calves'], null, false),
  ('Sprint', ARRAY['quads','hamstrings'], ARRAY['glutes','calves'], null, false),
  -- FOREARMS
  ('Wrist Curl', ARRAY['forearms'], ARRAY[]::text[], 'barbell', false),
  ('Reverse Wrist Curl', ARRAY['forearms'], ARRAY[]::text[], 'barbell', false),
  ('Plate Pinch', ARRAY['forearms'], ARRAY[]::text[], null, false),
  ('Wrist Roller', ARRAY['forearms'], ARRAY[]::text[], null, false),
  ('Gripper', ARRAY['forearms'], ARRAY[]::text[], null, false),
  ('Towel Pull-Up', ARRAY['forearms','lats'], ARRAY['biceps'], null, false),
  -- NECK
  ('Neck Extension', ARRAY['neck'], ARRAY[]::text[], null, false),
  ('Neck Flexion', ARRAY['neck'], ARRAY[]::text[], null, false),
  ('Neck Lateral Flexion', ARRAY['neck'], ARRAY[]::text[], null, false)
ON CONFLICT (name) WHERE (NOT is_custom) DO NOTHING;
